### ISSUE TITLE
Dead Link on Yellow/Red Loop Page

### ISSUE THREAD

**Issue by jslev9** [LoopKit/loopdocs#134]
On the Operate -> Troubleshoot -> Yellow/Red Loop page, under "Bluetooth/RL issues", the "Status Screen for Bluetooth" link (in the fifth bullet point) directs to a 404 error page.

Page on LoopDocs with bad link: https://loopkit.github.io/loopdocs/troubleshooting/yellow-red-loop/#bluetoothrl-issues
Link on the page that isn't working: https://loopkit.github.io/loopdocs/setup/loop-settings/rileylink_menu/#device

**Comment by metahgva** [comment]
Should this: https://loopkit.github.io/loopdocs/setup/loop-settings/rileylink_menu/#device be changed to this:
https://loopkit.github.io/loopdocs/operation/loop-settings/rileylink/#device

?

**Comment by jslev9** [comment]
I don't think so. I think it should be a screen shot of the iPhone's setting menu showing RL connected. 
Here's a screenshot of the affected page on LoopDocs:
![2019-10-04_8-33-13](https://user-images.githubusercontent.com/25287702/66207916-fb222780-e681-11e9-8568-787afc40bc86.jpg)

Here's a screenshot from my iPhone of what I think the image should be showing:
![iPhone settings](https://user-images.githubusercontent.com/25287702/66207972-19882300-e682-11e9-8348-3a94f1ae81cb.jpg)

**Comment by michaelshaver** [comment]
Not sure why I’m on this email list. Please remove me from it. Thanks

**Comment by marionbarker** [comment]
This page has changed.  There is now a new broken link on the same page.
https://loopkit.github.io/loopdocs/nightscout/mlab_cleanup/
is no longer found.
This is the first link at this location: https://loopkit.github.io/loopdocs/troubleshooting/yellow-red-loop/#resolving-frequent-red-loops about cleaning the mLab database.

**Comment by marionbarker** [comment]
Broken link fixed with PR 212
