### ISSUE TITLE
Dead link on the Grey circle trouble shooting page

### ISSUE THREAD

**Issue by leeodgers** [LoopKit/loopdocs#151]
Hello:

First time contributor.  I had a grey circle issue for the past two days.  
 
Under "Set Up App > Loop Displays there is the below comment.  When I clicked on the link, it is dead.  Thank you.  

A grey circle indicates the Loop is warming up and hasn’t yet completed its initial loop. When the Loop is first activated, it may take about 15-20 minutes to complete the first Loop, and the grey circle will be displayed. It needs CGM data to be gathered, so be patient. When it finally completes its first loop, the circle will turn green. If you can't get your grey loop to turn green, please see the Grey Loop troubleshooting page for tips.

**Comment by Kdisimone** [comment]
Ah thank you. I'll get that addressed. I did remove that page as the loop version improvements @ps2 made have made the likelihood of initial setups pretty much never get a grey loop and when they do the error message is much improved. 

It's nice to have a troubleshooting page finally reach its end of useful life.

**Comment by leeodgers** [comment]
Hi Katie:
Thank you for your continued dedication to this project and making lives
better for T1Ds and their caregivers.  It is truly appreciated.

I'm not sure why but I had a Grey circle over the weekend that would not go
away.  I was using Version 1.10.0 DEV on IOS 13.2.2 .  I had a Dexcom app
failure that asked me to delete the Dexcom app and reinstall.  I had to do
this several times.  That is when the Grey circle started.  Unfortunately
it would not go away no matter what I tried.   I ended up deleting the Loop
app, downgraded from DEV to V.1.9.6.  Restarted the install  from scratch
(with the help of your videos!).   Everything has been working fine for the
past 24 hours with the V.1.9.6.

Kindest regards,

Lee

**Comment by elnjensen** [comment]
@Kdisimone just saw a couple of people comment on this dead link in Facebook group in the past few days.  Looking at the old version of that page it still seems like useful advice in a concise list, but perhaps there's a better place to point people?

**Comment by bjornoleh** [comment]
Hi @Kdisimone, I was just searching Loopdocs for info on grey loops to help someone with such issues, and stumbled upon this dead link issue.

Someone on Looped reported persistent grey Loop issues just now, so apparently this is still a relevant topic. I don't know if that person is running an updated version of Loop or not.

**Comment by marionbarker** [comment]
There is still a broken link on this page: https://loopkit.github.io/loopdocs/operation/loop-settings/displays/#loop-status

This should be addressed.

**Comment by marionbarker** [comment]
Broken link fixed with PR 212.  Now points to Red Loop page.
