### ISSUE TITLE
Post 2 and Post 3 links for RileyLink carrying ideas are not loading

### ISSUE THREAD

**Issue by dybs** [LoopKit/loopdocs#164]
When I click the links for [Post 2](https://www.facebook.com/groups/TheLoopedGroup/permalink/2470906669792651/) or [Post 3](https://www.facebook.com/groups/TheLoopedGroup/permalink/2469724099910908/), I get the error below.
![image](https://user-images.githubusercontent.com/2606788/72488399-785b4d80-37d6-11ea-863f-0eb25b7f5969.png)

**Comment by marionbarker** [comment]
This is Issue about a links posted on Facebook Looped group.  I don't think it should be an Issue in LoopDocs.  Close?

**Comment by marionbarker** [comment]
The links have been replaced and the two RileyLink specific pages were updated with PR-219
* https://loopkit.github.io/loopdocs/build/step5/
* https://loopkit.github.io/loopdocs/faqs/rileylink-faqs/
