### ISSUE TITLE
Phrasing suggestions for quiz

### ISSUE THREAD

**Issue by dybs** [LoopKit/loopdocs#165]
The quiz posted on the Looped group is a fantastic training tool for new (and old) users.  I think it would be great to keep it available under the Announcements section, or even have a link to it somewhere on LoopDocs - maybe even on the home page so new users can get a sense of how much they may need to learn, and it also serves as a bit of a primer on what sort of information is available in the docs.

However, at least a couple of people seemed to get tripped up by the phrasing of some of the questions.  Suggested rewording:

1. When you get a red Loop, **one of the easiest first** troubleshooting steps **is** to.... 
change to...
When you get a red Loop, **the first** troubleshooting step **should be** to.... 

("one of the easiest" can somewhat subjective - for instance, if the RileyLink isn't quite as accessible as the phone, it may be easier for someone to restart the Loop app first.  Hence my suggestion to simply to just "the first troubleshooting step")

2. When you want to understand Loop's decisions about temp basal adjustments and boluses, you should be looking at (may select multiple):
change to...
When you want to understand Loop's decisions about temp basal adjustments and boluses, you should **at a minimum** be looking at (may select multiple):

(Although I did know the correct answer, I still answered "all of the above" because COB, IOB, and Override do go into the Predicted Glucose Curve - and part of understanding Loops decisions COULD include understanding how the prediction curve is generated, which requires looking at the other items.  Hence my suggestion to add "at a minimum" as a sort of hint.

3. More of a comment, not necessarily a suggestion - Regarding bolusing with no CGM data, I overlooked the "just like normal".  Maybe add "**without any additional steps**"?

**Comment by marionbarker** [comment]
This is Issue about a Quiz posted on Facebook Looped group.  I don't think it should be an Issue in LoopDocs.  Close?
