### ISSUE TITLE
Wrong release date in Loop v2.0 section

### ISSUE THREAD

**Issue by ssommer1980** [LoopKit/loopdocs#169]
**Page:** https://loopkit.github.io/loopdocs/faqs/branch-faqs/
**Section :** Loop v2.0
On December 31, 2020, Loop released Loop v2.0 
--> Assume it is 2019 :)

**Comment by marionbarker** [comment]
The indicated page was updated.  This Issue can be closed.

**Comment by marionbarker** [comment]
fixed a while ago.  Thanks.
