### ISSUE TITLE
Insulin Activity units unclear

### ISSUE THREAD

**Issue by Vlin-der** [LoopKit/loopdocs#176]
Hi, at the page about Glucose Prediction it is unclear to me how I should interpret the units for Insulin Activity.

In the formula for 
deltaBG_I[t] = ISF[t] x IA[t]
it says that Insulin Activity is in U/5min
https://loopkit.github.io/loopdocs/operation/algorithm/prediction/#total-insulin-effect-combining-boluses-and-temporary-basal-rates

In the formula for
ICE[t] = OA[t] + IA[t]
it says that Insulin Activity is in mg/dl/5min
https://loopkit.github.io/loopdocs/operation/algorithm/prediction/#dynamic-carbohydrate-absorption

Am I missing something (and can you please explain what) or is there an inconsistency in the docs?

**Comment by dpostle** [comment]
I was also confused.  Is it Insulin Effect, which is ΔBG calculated earlier as ISF * IA.  The formula is then:
ICE[t] = OA[t] + ΔBG[t]

**Comment by marionbarker** [comment]
Thanks for your comments - you are correct.
@Joerg-Schoemer - would you mind taking a look at this? Thanks much for your help in converting figures to equations.

**Comment by marionbarker** [comment]
@Joerg-Schoemer: If you wanted to take a crack at updated for the non-linear carb model added way back in Loop 2.0, the would be wonderful.

[Non-Linear Carb Model](https://loopkit.github.io/loopdocs/faqs/release-faqs/#non-linear-carb-model)

**Comment by Joerg-Schoemer** [comment]
I'll take a look at it.

@Vlin-der all $\Delta BG$ values are time derived. Maybe we could write $\dot{BG}$ instead to clarify.
At the end to get the BG we have to integrate:

$$ BG = BG_0 + \int{\dot{BG}dt} $$

**Comment by marionbarker** [comment]
Closing this issue.
