### ISSUE TITLE
iOS 1.31.1 Health App UI changed

### ISSUE THREAD

**Issue by jbowler** [LoopKit/loopdocs#177]
https://kdisimone.github.io/looptips/data/health/

Browse to:

"You can always check your HealthKit settings for by opening the Health App, clicking on Sources at the bottom bar, and then clicking on the app's name you are interested in, for example Loop."

Follow those instructions.  They don't work with iOS 1.13.1.  To wit:

1) Click on the heart-in-a-white-square app icon on a running iPhone.
2) Observe: "Summary", [profile picture] at the top.  At the "bottom bar", observe two icons, "[heart], sub-title "Summary",, [four square boxes, like the Windows icon] "Browse".

Scrolling through the whole page, looking for the word "Sources" shows nothing.  It does show "Apps" but that leads to a nasty marketing black hole.

**Comment by elnjensen** [comment]
Looks like Health permissions have moved to the Settings app.  Should now be Settings -> Health -> Data Access & Devices, then click through to permissions screens for the individual apps. 

@Kdisimone  Just looking through open issues here - let me know if you'd like me to PR changes for any of them, or whether there are more comprehensive edits in the works somewhere.

**Comment by marionbarker** [comment]
This page in loopdocs updated to recognize that iOS 12 and 13/14 have different menus for Health App.  
* https://loopkit.github.io/loopdocs/build/health/

The graphics still show iOS 12, but words were updated. (BTW - looptips is a different repository)
