### ISSUE TITLE
Suggestions for Loop docs

### ISSUE THREAD

**Issue by PJHNS** [LoopKit/loopdocs#18]
Hi. The Loop docs are really clear and useful. I was easily able to set up Loop. Thanks. Along the way, I noticed the following three small things that the doc authors might be interested in considering for the next version of the docs.

1. Could mention Dexcom G4 CGM via Nightscout Share Server (https://github.com/dabear/NightscoutShareServer) in the following places:
* Requirements > CGM
* Build > Installing
* Build > Configuration > CGM Selection

2. Could update references to the old "Minimum BG guard" in a few places:
* Use > Carb entries
* Use > Bolus
* Algorithm > Overview (in text and images)
* Algorithm > Temp basal adjustments (in text and images)

3. Could update references to the old "Target range" in a few places:
* Algorithm > Overview (in text and images)
* Algorithm > Temp basal adjustments (in text and images)
* Algorithm > Bolus recommendations (in text and images)

**Comment by marionbarker** [comment]
This issue should be closed.
