### ISSUE TITLE
Bolus may not have succeeded 

### ISSUE THREAD

**Issue by MoniqueCambreyYoung** [LoopKit/loopdocs#180]
I’m using a Medtronic 715 pump with loop v2.0 on a iPhone running 13.3 - almost every time bar about 3 in the past 7 days that I have tried to bolus through the loop app I get a notification that my bolus may not have succeeded, however the bolus goes through the pump and once finished registers as IOB. 

The message reads 
Bolus 
3.2 U bolus may not have succeeded 
Invalid response during PumpMessage(Carelink, bolus, 029854, 012000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000):a9657265a9745665dd3d07a9756265a974c6556c6a6500. Check you pump before retrying. 

Loop report attached

**Comment by Kdisimone** [comment]
This is the Issues list for Loopdocs, not Loop itself.  Please head over to github.com/loopkit/loop if you'd like to report issues with Loop.  However, this sounds like a temporary probably and you should update your loop app as a first step to addressing the issue.
