### ISSUE TITLE
What is "delivery glags?"

### ISSUE THREAD

**Issue by dfdumaresq** [LoopKit/loopdocs#187]
Is the word 'glags' a typo? It doesn't google. It's found [here](https://loopkit.github.io/loopdocs/troubleshooting/uncertain-bolus/)

![image](https://user-images.githubusercontent.com/20051/89138685-30d9ac00-d4f1-11ea-8fbb-15d2c5c69489.png)

If it is actually a term, please provide a definition or better still use a lay-person's word.

Thanks!

**Comment by Kdisimone** [comment]
Just a typo. Should be "logs"
