### ISSUE TITLE
Possible need to update or clarify documentation

### ISSUE THREAD

**Issue by msinkovich** [LoopKit/loopdocs#20]
In the Setup->Install Loop->Code Customizations section the Loop Graph Hours says to modify line 157.  I think it should be ~192 if memory serves.

Also the customization of "Want 1/2 of my Insulin Action Duration to show in the future?"
X-Code wouldn't accept the custom code as provided and I was not able to use the customization...

**Comment by Kdisimone** [comment]
docs have been updated to fix the line numbering, and the code modifications have been updated to help.  thanks
