### ISSUE TITLE
mLab cleanup link broken

### ISSUE THREAD

**Issue by Nightfoxy** [LoopKit/loopdocs#208]
This link no longer works: https://loopkit.github.io/loopdocs/nightscout/mlab_cleanup/

It is linked on this page in the first line of the paragraph:
https://loopkit.github.io/loopdocs/troubleshooting/yellow-red-loop/#resolving-frequent-red-loops

I'm not sure if a DB repair is needed anymore. I would encourage the CGMitC group to update the NS docs with the details.

**Comment by bjornoleh** [comment]
Here isa link to view an earlier version of that page

https://github.com/LoopKit/loopdocs/blob/31c8b9607ad8c2b03bf1aa485b7433aa5fe50b72/docs/nightscout/mlab_cleanup.md

The current NS Admin tool instructions are here, for deleting old data etc. 

http://nightscout.github.io/nightscout/admin_tools/#database-maintenance

I don't know if a repair database like in MLab is needed with Atlas.

Here are the current Cleanup steps for the various services that are used with NS. 

http://nightscout.github.io/troubleshoot/cleanup/

@psonnera, do you know if there is anything like the MLab repair database in Atlas, or if that is required?

**Comment by marionbarker** [comment]
I am in the process of updating yellow-red-loop.md and fixing the link. (I am using my repo for content update. Christian is ensuring markdown formatting is correct.) With all the flux I expect with the upcoming site cleanup, please continue using Issues for reporting problems, rather than PR. I will close each issue after the content is updated, reviewed and merged into this repo.

**Comment by marionbarker** [comment]
Please review this page (this is a staging area for changes that will be made to loopdocs soon).
https://marionbarker.github.io/loopdocs/troubleshooting/yellow-red-loop/

**Comment by Nightfoxy** [comment]
No problem. I had someone send me a message asking how to clean mlab due to
red loops. No rush.

**Comment by psonnera** [comment]
@bjornoleh looking into the mongoDB documentation I don't see anything that could be done with the web interface like with mLab. I'd stick to routine maintenance provided by Nightscout admin tools http://nightscout.github.io/troubleshoot/troublehoot/#database-full and worst case like in cleanup http://nightscout.github.io/troubleshoot/troublehoot/#reports-slow-loading-or-timeout

**Comment by bjornoleh** [comment]
Ok, thanks @psonnera

lør. 13. mar. 2021, 11:14 skrev Patrick Sonnerat ***@***.***>:

**Comment by marionbarker** [comment]
Fixed with PR 212.  Just use database and don't specify mLab.  Also point to new Nightscout documentation and remove from loopdocs.
