### ISSUE TITLE
Place Glucose Monitor Source into a sub menu

### ISSUE THREAD

**Issue by pianoman2222** [LoopKit/loopdocs#22]
About once every 2 months while changing a setting (basal rate, carb ratio, etc...) I inevitably turn **off** my G5 transmitter button by scrolling up/down on the screen (ie, my thumb inadvertently taps the button and turns it off or turns on a different glucose source). This wipes my G5 transmitter ID, so I have to retype it.

I wanted to make a request to put all of the the Continuous Glucose Monitor sources in a sub menu to avoid this problem.

**Comment by Kdisimone** [comment]
@pianoman2222 You probably want to make this as an issue over in the LoopKit/Loop repository as it is an issue with the code (not the loopdocs).  I'll close this out, but feel free to add it over to the Loop issues if someone hasn't already made same feature request.
