### ISSUE TITLE
Dead link / 404

### ISSUE THREAD

**Issue by bjornoleh** [LoopKit/loopdocs#234]
Dead link / 404

https://loopkit.github.io/loopdocs/operation/algorithm/overview/temp_basal
![image](https://user-images.githubusercontent.com/63544115/129004603-14306c1c-fd76-4662-bd94-66dcba58e761.png)

This link is found here:
https://loopkit.github.io/loopdocs/operation/algorithm/overview/#overview

**Comment by marionbarker** [comment]
Thanks for pointing this out.
