### ISSUE TITLE
Install Xcode from .xip download 

### ISSUE THREAD

**Issue by bjornoleh** [LoopKit/loopdocs#272]
I tested an alternative approach when updating to Xcode 13:

When logged into the Apple Developer website, you can download Xcode as an .xip file. This is a compressed file that you extract by double-clicking it similarly to a .zip file. 

After extracting the file in Finder, drag and drop it into the Applications folder, and the installation will begin. You will be asked to replace or keep the old one. You should replace it so you don't end up with several versions of Xcode. 

After installing, you can delete the .xip file. 

This process takes a little time for each step:

1. Download Xcode .xip
2. Extract .xip
3. Install Xcode into Applications 

But the total amount of time is insignificant compared to the App Store  update/install.

You still need a lot of space for the download/extract/install steps.

Direct link for Xcode 13:
https://download.developer.apple.com/Developer_Tools/Xcode_13/Xcode_13.xip

The link was found here:
https://developer.apple.com/download/all/

One of many guides for Xcode .xip install:
https://www.freecodecamp.org/news/how-to-download-and-install-xcode/

Perhaps this is something to include in Loopdocs? I have seen people get failing App Store update after 24 hours. That is a lot of wasted time!

**Comment by marionbarker** [comment]
Closed with pull request #274
