### ISSUE TITLE
Feature- temporary settings option

### ISSUE THREAD

**Issue by edeny16** [LoopKit/loopdocs#273]
Add an option for temporary plan (for limited time as decided by user) with new settings- ISF,basal, correction range , etc..

**Comment by marionbarker** [comment]
This repository is only for documentation.  And to save you time, here are two links in the repo (LoopKit/Loop) where that Feature Request already exists so please don't start a new one.  

* Aug 9, 2016
  * https://github.com/LoopKit/Loop/issues/114

* Dec 22, 2016
  * https://github.com/LoopKit/Loop/issues/331
