### ISSUE TITLE
Potential typos and clarification request for Blood Glucose Prediction

### ISSUE THREAD

**Issue by jminlee97** [LoopKit/loopdocs#280]
Hi, I've been reviewing the Blood Glucose Prediction page to reimplement this algorithm in python, and have some questions about some of the calculations.

1. In the Dynamic Carbohydrate Absorption section, it says that ICE[t] = OA[t] + IA[t].  Since insulin activity is negative, shouldn't this be ICE = OA - IA instead? Or put differently, ICE + IA = OA?

2.  In the Retrospective Correction Effect, blood glucose velocity (BG_vel) is used to calculate the retrospective correction effect. I have two questions regarding this calculation. 
    - How exactly is retrospective forecast (RF) calculated? My initial understanding was that this would simply be the _first 30 minutes of the prediction Loop made 30 minutes ago._ However, this definition breaks down in situations such as this. 
    
        - At t-30 minutes: Loop makes a prediction. We use the first 30 minutes of this prediction as RF.
        - At t-20 minutes: User gives themselves an insulin bolus. 
        - At t minutes: BG_vel is calculated using the difference between RF and the last 30 minutes of BG. However, while retrospective correction is supposed to capture the effects that are not modeled by insulin and carbs, this difference will also include the effects of insulin given at t-20 minutes. 
        
        - I think there is some ambiguity regarding how RF is calculated. A more detailed description would be extremely helpful. 

    - In addition, BG_vel captures how 'off' Loop's prediction is to the true BG values. If BG_vel is positive, Loop's estimations are too high. If BG_vel is negative, Loop's estimations are too low. To account for this, if BG_vel is positive we should be subtracting from Loop's estimation, and if BG_vel is negative we should be adding to Loop's estimation. However, when blending all the effects, we _add_ the retrospective correction effects. Shouldn't we be subtracting this instead, or define BG_vel as the mean of (BG - RF)?

**Comment by marionbarker** [comment]
I saw some conversation on zulipchat with Dragan so will close this Issue.  I still have Issue #176 open to remind me to fix the typos.  Feel free to reach out if you believe this needs to stay open.
