### ISSUE TITLE
Supplemental info for direct download of Xcode

### ISSUE THREAD

**Issue by bjornoleh** [LoopKit/loopdocs#283]
https://loopkit.github.io/loopdocs/build/updating/#direct-download-of-xcode

I notice some confusion in the forums regarding direct download of Xcode. Perhaps we need some additional info to clarify the process.

When installing the extracted Xcode app by dragging into the Applications folder, there is a prompt asking "An item named “Xcode” already exists in this location. Do you want to replace it with the one you’re moving?" (Keep Both / Stop / Replace)

The user should select "Replace" here to avoid ending up with two different versions of Xcode. This may create other issues, e.g. when using the script to open Xcode (xed .) I could not see any issues with two copies of the same version of Xcode, but perhaps with different versions it will be an issue. It will take up space anyways.

Finally, the user can delete the .xip file when done.

When choosing Replace, App Store will not know about the current .xip install. If visiting App Store, there is no option to update Xcode, but it will be possible to download again. This would also lead to duplicate Xcode. Perhaps worth mentioning.

<img width="930" alt="Screenshot 2021-10-28 at 13 15 32" src="https://user-images.githubusercontent.com/63544115/139245604-2dd297e2-3654-4762-8a79-66d3b24c673e.png">

Adding some other potential screenshots:
Extracting .xip:
<img width="925" alt="Screenshot 2021-10-28 at 13 09 50" src="https://user-images.githubusercontent.com/63544115/139244591-74a5776b-8c84-4518-9d29-ca1dbc393b9d.png">

Extracted Xcode:
<img width="930" alt="Screenshot 2021-10-28 at 13 12 45" src="https://user-images.githubusercontent.com/63544115/139245069-a44492fe-8c03-45c0-b75d-92e292a36a99.png">

Duplicate Xcode (by extracting the same .xip twice. Might look different if the first version was from App Store)
<img width="932" alt="Screenshot 2021-10-28 at 13 20 56" src="https://user-images.githubusercontent.com/63544115/139246485-cb234074-e4c5-441f-b3e4-5a82cd60df5a.png">

**Comment by marionbarker** [comment]
I did not review this when modifying direct download section (went from memory).  I did make changes with PR #285 that I think are sufficient. And first time I looked for xcode in Apple Store while I had one installed, I didn't see it. Then put Xcode in trash and could see it.  But now I have Xcode restored and I see Xcode 13.1 in Apple Store (but still not in updates). So my instructions may be slightly inaccurate, but I think they are good-enough for the average LoopDocs user.

I'm going to close this for now but feel free to come back and say I really need to add something more to LoopDocs.

**Comment by bjornoleh** [comment]
Hi, great updates to the docs!

A couple of minor comments:

1. When doing the direct download of Xcode, Xcode does show up in App Store. There is just not the option of updating your current install, as App Store seems to be oblivious to what you have. It is possible to click the download button in App Store though.  In my test doing this, I ended up with only one install of Xcode,  and from that point the version was recognised by App Store.

"warning "Direct Download"

  - If you previously did a direct download of Xcode, it will not show up in the Apple Store."

2. I suppose it is "App Store" and not "Apple Store"

Sorry about the nitpicing :-)

**Comment by bjornoleh** [comment]
Point 2. above should be fixed with https://github.com/LoopKit/loopdocs/pull/286/commits/1312d7936cc48ab9073d0ee9db68a41d8b99aa4b
