### ISSUE TITLE
Loopdocs search is too restrictive

### ISSUE THREAD

**Issue by bjornoleh** [LoopKit/loopdocs#284]
It would be good if the Loopdocs search gave results for partial hits, not only complete words.

Example: someone who have heard about  Zulip will not get results by searching only for "Zulip", they would have to know that it is called Zulipchat in Loopdocs. 

https://loopkit.github.io/loopdocs/#stay-in-the-loop

![Screenshot_20211030-114814_Chrome](https://user-images.githubusercontent.com/63544115/139528263-bc7e73be-829a-4f31-b7a3-88385c927785.jpg)

![Screenshot_20211030-114831_Chrome](https://user-images.githubusercontent.com/63544115/139528279-0171b40b-7119-4148-a508-7ea81bc2c2bd.jpg)

**Comment by marionbarker** [comment]
I'm happy to make the modifications. Not sure how to do it.

@cfaagaard - Christian - do you have a suggestion?

**Comment by cfaagaard** [comment]
You can just use * in front or at the end of your searc-word.

**Comment by cfaagaard** [comment]
Mkdocs uses lunr, here you can see how you can search: https://lunrjs.com/guides/searching.html

**Comment by bjornoleh** [comment]
> You can just put a * in front or at the end of your search-word. Or both...

Thanks, yes that works. But I don't really expect people to know this. Perhaps it isn't possible to change the search behaviour,  but if it is, I think that would make a difference to some.

**Comment by cfaagaard** [comment]
So you want wildcards as a standard.... Front and back? This will give too many results for a normal search. 
Maybe a description of how to search in loopdocs would be better.

**Comment by bjornoleh** [comment]
Perhaps a trailing wildcard would be acceptable? Then you would also see the number of results decrease as the search word is typed out. 

In the example above with Zulio, the user might think they had gotten it all wrong when getting no results at first.

Of course a helper page for searching could help, but that will soon be forgotten about I am afraid.

**Comment by bjornoleh** [comment]
I did a quick test with trailing wildcard. It looks good to me, and I would not mind this as the default behaviour. Both for myself and for anyone who is not familiar with Boolean operators and how to refine a search. 

These days people are spoilt with advanced searching tools like Google search, and Boolean operators are probably about to be as unknown as Dos commands.

![Screenshot_20211031-093240_Chrome](https://user-images.githubusercontent.com/63544115/139574853-c83b38de-9426-44b0-b718-94ff1c5efac0.jpg)

![Screenshot_20211031-093318_Chrome](https://user-images.githubusercontent.com/63544115/139574859-5a98edab-9ec7-450c-b809-7ee8d557c45c.jpg)

![Screenshot_20211031-093347_Chrome](https://user-images.githubusercontent.com/63544115/139574870-76709414-a2ab-4c67-b5b6-7cfa8fd1c230.jpg)

Please notice how the last result include relevant hits that woukd require two different searches without the trailing wildcard.

**Comment by cfaagaard** [comment]
Looked into this:
mkdocs has decided that kind of functionality ("changing the default search behaviour") is not going to a part of mkdocs: https://github.com/mkdocs/mkdocs/issues/1914#issuecomment-561179783
They state is should be a theme implementation.
Loopdocs use flatly as theme (via mkdocs-bootswatch.): http://mkdocs.github.io/mkdocs-bootswatch/
And flatly do not have this functionality.

So if we want this functionality we have to choices:
1. we need to implement it our self by customzing the theme and thereby having "the extra work" of maintaining this custom theme when we upgrade mkdocs/flatly (as Marion just did the other day without any problems).
2. Change theme that as this kind of functionality. When I did the setup for the translation of loopdocs I used the theme "Materiale" as the current theme "flatly" is old and not maintained. It has this kind of functionality. You can see a old version of loopdocs in action here with that kind of functionality: https://loopdocs.github.io/loopdocs/en/

**Comment by bjornoleh** [comment]
Thanks for looking into this! 

The newer Material theme looks a bit more up to date and seems more responsive on a phone. The default search here is also how I would have expected it to work. 

The overall look is a bit different, and might have some other implications, perhaps requiring some editing of the contents/formatting. If the switch is not too onerous, perhaps it's an idea to change to a theme that is being maintained? 

I have very little understand about the total implications though.

**Comment by cfaagaard** [comment]
I have justed tested the current version of loopdocs (in a fork :-), so no changes in master) with the newest material version. You can see the result here:
https://myloopdocstest.github.io/loopdocs/

And it looks like there are some work to be done if we are going to move to this theme.

The fork is here: https://github.com/MyLoopdocsTest/loopdocs

You can see my changes in the commits to run this theme (it is only in requriements.txt and mkdocs.yml)

**Comment by marionbarker** [comment]
I implemented the changes to requirements.txt and mkdocs.yml from @cfaagaard (as of his commit d18b60e) this morning, in a new branch (new-theme) of my repo and it looks pretty good to me. I don't see any "debris" such as the {width = #} that was in his pages.

(I did the pip install -r requirements.txt before building and I built from my laptop - not the auto-publish on github).

https://marionbarker.github.io/loopdocs/

I'll put this out for comments before implementing this change - it is different but I think in a better way.

**Comment by cfaagaard** [comment]
Great. I think there is something is going on with the custom css. 
![Screenshot_20211031-171108](https://user-images.githubusercontent.com/25353502/139592524-008d44e9-a63c-4775-aac8-b7bf1aebb226.png)
Maybe remove the whole custom css....

**Comment by cfaagaard** [comment]
Same page with no custom css
![Screenshot_20211031-174800](https://user-images.githubusercontent.com/25353502/139593845-bca8a0e3-99bb-4d46-be97-832ef01114d2.png)

**Comment by cfaagaard** [comment]
With material there loads of options to configure the site with different functionality: https://squidfunk.github.io/mkdocs-material/

I just implemented a pencil-icon on each page so one can edit the page in github directly. (Just to see how it works) https://myloopdocstest.github.io/loopdocs/

Earlier this year I tested github-issue/comment integration here (scroll down to the bottom of the pages): https://cfaagaard.github.io/MultiLangTest/en/
Here one can comment directly on the page.

**Comment by marionbarker** [comment]
Thanks for pointing the way Christian.

I'm not going to put all my "playing around" stuff in this conversation.  I'm doing incremental commits.  I have changed color scheme and added a logo.

The problem you were noticing in the spacing of the icon that got added to the admonitions with this theme was addressed by a change in admonitions.css.

**Comment by Nightfoxy** [comment]
It's very nice looking! The menu works beautifully on my phone.

Kenny Fox

**Comment by elnjensen** [comment]
I like it - definitely an improvement in searching.   I haven’t played around enough overall to comment on organization/ navigation, but seems fine there too.

Regarding search, is there any way to have a search return an actual page of search results, rather than a transient floating popup?  When I’m not sure what page I want, and there are multiple hits in the search result, it’s annoying to have to redo the search every time I want to try a different page to see if it has the info I’m looking for.

**Comment by marionbarker** [comment]
Yes Eric - right click on the interesting search result and open in new tab.  You can work your way down the list.
