### ISSUE TITLE
Disable TouchID for Bolus

### ISSUE THREAD

**Issue by CrushingT1D** [LoopKit/loopdocs#29]
Disable TouchID for Bolus instructions are out of date. Assume the code was modified since this was added to the example customizations.

https://loopkit.github.io/loopdocs/setup/build/code_customization/

**Comment by Kdisimone** [comment]
I just tested it and the instructions still worked as intended for me.  What behavior are you seeing that made you think the instructions aren't correct?

**Comment by marionbarker** [comment]
The page has been updated to include FaceID as well as TouchID.  This issue should be closed.
