### ISSUE TITLE
Error messages caused by low phone storage

### ISSUE THREAD

**Issue by bjornoleh** [LoopKit/loopdocs#290]
Someone reported this:

![FB_IMG_1635973268832](https://user-images.githubusercontent.com/63544115/140193275-596a8bea-d1e6-446b-a21c-d4c199569b70.jpg)

![FB_IMG_1635973274574](https://user-images.githubusercontent.com/63544115/140193277-dab9ca3b-0086-4e94-8438-9c299dbfdac5.jpg)

The G6 app is saying it is no longer functioning properly (without explaining why), and it is suggesting deleting and reinstalling the app.

In Loop, there is a message about Sqlite error / Database or disk is full.

I could not find this in Loopdocs, and I haven't seen it before. But others had, and said deleting stuff to free up space, and sometimes also reinstalling usually helps.

**Comment by bjornoleh** [comment]
The user reports that deleting stuff to free up space was successful (deleting other unrelated app) after a reboot of the phone.

**Comment by marionbarker** [comment]
Closed with PR #293
