### ISSUE TITLE
Expand on the workings of overrides, recommended practices, what to avoid and why.

### ISSUE THREAD

**Issue by bjornoleh** [LoopKit/loopdocs#294]
This section is good, but often overlooked and misunderstood. Some clarification and restructuring of this part might help.

https://loopkit.github.io/loopdocs/operation/features/workout/?h=sledgehammer#how-overrides-do-not-work

A useful discussion on FB for reference:

https://www.facebook.com/groups/TheLoopedGroup/permalink/2980475585502421/

My input to the discussion above:

... [for] anyone else wondering why, and for how long the prediction might be messed up with extreme overrides:

The prediction curve is based on the ISF and CR settings in Loop at the time of a carb entry or bolus. You can turn off an override from here on out, but you won't be cancelling the override setting for the time that has already passed. 

Hence, the override-modified ISF and CR at the time of your bolus or carb entry will last as long as the entry does. As we all know, insulin is modelled to last for 6 hours. And a meal last until it is observed by Loop as fully absorbed, or until it times out at 1.5 x the entered absorption time. So if you do get the prediction messed up, it can last for hours.

A typical scenario is the "sledgehammer" method described in Loopdocs: An exteme low 10 % override is activated to stop insulin delivery due to fear of a low, or even after the low happened. Then, as the situation is over, the override might be forgotten, and is still active. A bolus given at this point will be considered by Loop as having 10 x the BG lowering effect! This is a typical cause of extremely low eventual BG predictions such as -500 mg/dL (-30 mmol/L).

The better approach to stop insulin delivery is to use a very high target instead. As long as it is higher than the predicted eventual BG, Loop will reduce or stop basal delivery. Pick a really high target, and Loop will surely zero-temp.

I hope that makes things a little clearer, as the warning against wreaking havoc with the prediction might be a little abstract.

Here is the relevant section in Loopdocs,  by the way. It is already described pretty well, but since this is often misunderstood or overlooked, perhaps it could be made even clearer. I have been thinking about suggesting a change, but don't know when I'll get around to that.

https://loopkit.github.io/loopdocs/operation/features/workout/?h=sledgehammer#how-overrides-do-not-work

**Comment by bjornoleh** [comment]
Another typical sample of override-induced extreme negative predictionsv

https://www.facebook.com/groups/TheLoopedGroup/permalink/2984123881804258/

**Comment by marionbarker** [comment]
I think we have covered this.  Please review the most recent version and re-open the issue with specific concerns if you think we have missed something.
