### ISSUE TITLE
Update safely to iOS 15

### ISSUE THREAD

**Issue by bjornoleh** [LoopKit/loopdocs#296]
The issue with Loop crashing when updating to iOS 15 if last built with Xcode 12.4 is described in Loopdocs. But the description might be read as “ do not install iOS 15” [period]. 

The text should be changed a bit with a description of what to do to safely update to iOS 15 

e.g  “Make sure to update MacOS first, then Xcode, then build to the phone as is. Once you made a successful build using Xcode 13, you can update the phone too. Otherwise,Loop is likely to crash and will need a rebuild and a lengthy update process of MacOS and Xcode if this was not done yet.”

Or something to that effect. 

https://loopkit.github.io/loopdocs/build/updating/#when-to-update-loop

iOS 15 Warning
Any Loop app built with Xcode version prior to Xcode 12.5 will immediately fail when the phone is updated to iOS 15. If you last built Loop with Catalina do not install iOS 15.

Follow this link, Xcode version, for instructions to determine what version was used when building the Loop app currently on your phone.

https://loopkit.github.io/loopdocs/faqs/update-faqs/#how-can-i-confirm-xcode-version-i-used

DO NOT INSTALL iOS 15 if the Xcode version on your Loop build is 12D or earlier - the Loop app will immediately stop working and you will have to rebuild Loop.

**Comment by marionbarker** [comment]
Close with PR #297
