### ISSUE TITLE
Add Loop Follow to Loop Notifications

### ISSUE THREAD

**Issue by DonaldBough** [LoopKit/loopdocs#313]
I just ran into LoopFollow and it seems to be one of the few apps with completely adjustable, and silencable blood sugar alarms that are more customizable than Sugarmate.

It's a shame I couldn't have seen this immediately from the docs. Could we mention LoopFollow ([repo link](https://github.com/jonfawcett/LoopFollow) ) under the "Remote Notifications" section of the Loop Notifications page?

**Comment by marionbarker** [comment]
I’ll review the docs to see if an additional link should be added. Loop Follow is already in LoopDocs. 

https://loopkit.github.io/loopdocs/nightscout/ns_crossref/?h=loop+foll#loop-follow

**Comment by marionbarker** [comment]
I think this is covered with earlier changes plus PR #435
