### ISSUE TITLE
Suggestion: remove blocks with pre-populated choices for build script options

### ISSUE THREAD

**Issue by codybj** [LoopKit/loopdocs#318]
The multi line code blocks provided in step 14 (e.g. to launch the build script and choose loop master and open Xcode) seem to be the source of a lot of confusion for a lot of users who are unfamiliar with the command line. They attempt to paste the whole block and expect to be able to choose other options such as cleaning provisioning profiles. Many  questions have been posted to the Looped Facebook group due to this misunderstanding. 

I suggest to remove these "convenience" multi line commands from the docs and provide only the shell script line. Users should follow the instructions to choose the desired options interactively.

**Comment by marionbarker** [comment]
close with PR #319
