### ISSUE TITLE
NaN

### ISSUE THREAD

**Issue by blankec** [LoopKit/loopdocs#41]
I can't loop. Getting a green circle, and the app can tell my pump to bolus, but it won't predict  glucose and will not give me a basal rate (adjustment). I changed the pump battery and that worked for an hour, then everything reverted to not working. The only other abnormality is I briefly get an exclamation point near the CGM readout. I have turned everything on and off multiple times.

I am near the end of the sensor (8.5) days. Is that possibly responsible? Should I just change it? Any other fixes? I miss my looping! 

![Image-1](https://user-images.githubusercontent.com/52581062/60742651-08186900-9f23-11e9-8890-76b4e379dd05.jpg)

**Comment by ps2** [comment]
Please attach an issue report.

**Comment by blankec** [comment]
I can't loop. Getting a green circle, and the app can tell my pump to bolus, but it won't predict glucose and will not give me a basal rate (adjustment). I changed the pump battery and that worked for an hour, then everything reverted to not working. The only other abnormality is I briefly get an exclamation point near the CGM readout. I have turned everything on and off multiple times.
I am near the end of the sensor (8.5) days. Is that possibly responsible? Should I just change it? Any other fixes? I miss my looping!
[cid:image001.png@01D53330.5D9C0350]

**Comment by ps2** [comment]
To attach an issue report, please go to Loop settings, then tap "Issue Report", then send it to yourself, zip it up and attach it to this ticket.

**Comment by blankec** [comment]
Sorry-I don’t understand. Text it to myself? Then, how do I “zip it up”?

Thanks-

CHARLES D. BLANKE

**Comment by blankec** [comment]
The instructions at the site simply say to "share" with myself, but same problem. Share how? Text? Email? Dropbox? Sorry to be so non-techy.

**Comment by blankec** [comment]
Same bug in the program


NaN

[cid:image001.png@01D54089.7DBBE220]

From: Blanke Portland <blankec@ohsu.edu>
Date: Friday, July 5, 2019 at 12:55 PM
To: LoopKit/loopdocs <reply@reply.github.com>
Subject: Re: [LoopKit/loopdocs] NaN (#41)

Sorry-I don’t understand. Text it to myself? Then, how do I “zip it up”?

Thanks-

CHARLES D. BLANKE

**Comment by Kdisimone** [comment]
Charles, email the issue report to yourself and then drag and drop the email attachment (issue report) into a new comment here. That will post it. Easiest to do the drag and drop on computer

**Comment by blankec** [comment]
About once per week my predicted glucose will go from some finite value to NaN (not a number). It does NOT occur after I make any kind of adjustment or override-just comes out of nowhere. Each time I replace the pump battery, turn the Riley and phone off and on, and open and close Loop. I can still bolus (I have a green loop) but the auto basal adjustments disappear. Last time this lasted about two hours and then spontaneously resolved; today I had NaN for 6 hours.

Any and all advice welcome.

CHARLES D. BLANKE, M.D.
 blanke@ohsu.edu<mailto:blanke@ohsu.edu>

**Comment by marionbarker** [comment]
I believe this issue should be closed.  (Filed in the wrong place and I think this has been dealt with.)
