### ISSUE TITLE
Loop quit unexpectedly

### ISSUE THREAD

**Issue by prichardson211** [LoopKit/loopdocs#459]
Hi,

My loop app crashes anytime I leave it on too long.  If I open it for a minute (not quite long enough to crash the app) my phone will get very hot and begin to show signs of low memory for running other apps.  I caught the error message in Xcode:

-------------------------------------------------------------------------------
Details

The app “Loop” on ThePhone quit unexpectedly.
Domain: IDEDebugSessionErrorDomain
Code: 10
Failure Reason: Message from debugger: Terminated due to memory issue
User Info: {
    DVTErrorCreationDateKey = "2022-10-13 13:08:42 +0000";
    IDERunOperationFailingWorker = DBGLLDBLauncher;
}
--

Analytics Event: com.apple.dt.IDERunOperationWorkerFinished : {
    "device_model" = "iPhone14,4";
    "device_osBuild" = "15.6.1 (19G82)";
    "device_platform" = "com.apple.platform.iphoneos";
    "launchSession_schemeCommand" = Run;
    "launchSession_state" = 2;
    "launchSession_targetArch" = arm64;
    "operation_duration_ms" = 125128;
    "operation_errorCode" = 10;
    "operation_errorDomain" = IDEDebugSessionErrorDomain;
    "operation_errorWorker" = DBGLLDBLauncher;
    "operation_name" = IDEiPhoneRunOperationWorkerGroup;
    "param_consoleMode" = 0;
    "param_debugger_attachToExtensions" = 0;
    "param_debugger_attachToXPC" = 1;
    "param_debugger_type" = 5;
    "param_destination_isProxy" = 0;
    "param_destination_platform" = "com.apple.platform.iphoneos";
    "param_diag_MainThreadChecker_stopOnIssue" = 0;
    "param_diag_MallocStackLogging_enableDuringAttach" = 0;
    "param_diag_MallocStackLogging_enableForXPC" = 1;
    "param_diag_allowLocationSimulation" = 1;
    "param_diag_gpu_frameCapture_enable" = 0;
    "param_diag_gpu_shaderValidation_enable" = 0;
    "param_diag_gpu_validation_enable" = 0;
    "param_diag_memoryGraphOnResourceException" = 0;
    "param_diag_queueDebugging_enable" = 1;
    "param_diag_runtimeProfile_generate" = 0;
    "param_diag_sanitizer_asan_enable" = 0;
    "param_diag_sanitizer_tsan_enable" = 0;
    "param_diag_sanitizer_tsan_stopOnIssue" = 0;
    "param_diag_sanitizer_ubsan_stopOnIssue" = 0;
    "param_diag_showNonLocalizedStrings" = 0;
    "param_diag_viewDebugging_enabled" = 1;
    "param_diag_viewDebugging_insertDylibOnLaunch" = 1;
    "param_install_style" = 0;
    "param_launcher_UID" = 2;
    "param_launcher_allowDeviceSensorReplayData" = 0;
    "param_launcher_kind" = 0;
    "param_launcher_style" = 0;
    "param_launcher_substyle" = 0;
    "param_runnable_appExtensionHostRunMode" = 0;
    "param_runnable_productType" = "com.apple.product-type.application";
    "param_runnable_swiftVersion" = "5.6.1";
    "param_runnable_type" = 2;
    "param_testing_launchedForTesting" = 0;
    "param_testing_suppressSimulatorApp" = 0;
    "param_testing_usingCLI" = 0;
    "sdk_canonicalName" = "iphoneos15.5";
    "sdk_osVersion" = "15.5";
    "sdk_variant" = iphoneos;
}
--

System Information

macOS Version 12.5 (Build 21G72)
Xcode 13.4.1 (20504) (Build 13F100)
Timestamp: 2022-10-13T06:08:42-07:00 
------------------------------------------------------------

Please let me know if there is any more information I can provide to help debug this issue.

**Comment by marionbarker** [comment]
An issue report for the code needs to be filed at LoopKit/Loop (not the documentation site loopdocs).
Also - I believe this is a phone problem, not a code problem.
You are best off asking for help in [Loop Zulipchat](https://loop.zulipchat.com).

I'll alert the developers over there that you posted this.
I'm closing this Issue. What that means is it doesn't show up as "open" but all the information you posted is still here, available for review and the conversation can continue.

**Comment by marionbarker** [comment]
The location in zulipchat where I posted this issue is https://loop.zulipchat.com/#narrow/stream/148543-Loop/topic/Memory.20Error/near/303837498
