### ISSUE TITLE
Block OTA iOS Update | Document Workaround

### ISSUE THREAD

**Issue by zachvanduyn** [LoopKit/loopdocs#467]
**Example(s):**

1. [https://loopkit.github.io/loopdocs/build/updating/](https://loopkit.github.io/loopdocs/build/updating/) - **Section:** _iOS 15 Warning - Check Before You Update_

 

2. [https://loopkit.github.io/loopdocs/build/step2/#turn-off-automatic-updates]( https://loopkit.github.io/loopdocs/build/step2/#turn-off-automatic-updates)

Multiple times throughout the documentation, the user is reminded about the risk associated with updating iOS. Obviously turning off automatic updates is a good first step. For something a bit more restrictive (i.e. for those of us with dated hardware on the Macbook side & who cannot build against the latest iOS) you can install a configuration profile that'll disable OTA updates. This restriction is reversible by removing the profile.

Reference: https://ios.cfw.guide/blocking-updates/

Profile Hotlink: https://cydia.ichitaso.com/no-ota15.mobileconfig

Video: https://www.youtube.com/watch?v=cBv9lW1zX1g

This was helpful for our family, but I did want to explore if this is worth sharing / incorporating into documentation. If other people seem to be fine without it, we can disregard this issue.

Thanks!

-ZVD

**Comment by marionbarker** [comment]
Thanks - I'm going to stick with what is in LoopDocs for now.  Leaving this open so I can think about it later.

**Comment by marionbarker** [comment]
With the advent of browser build, the concern of not being able to update your mac to build Loop has been alleviated.
