### ISSUE TITLE
Operation couldn’t be completed- Share client share error

### ISSUE THREAD

**Issue by ashbyakgm-marie** [LoopKit/loopdocs#48]
![E3D2B485-928D-4B9F-BC8F-63CC67794B09](https://user-images.githubusercontent.com/54404009/63515952-a18ae280-c4b1-11e9-8286-eb474f6648ed.jpeg)

**Comment by Kdisimone** [comment]
I think you probably meant to file this as an issue in Loop (vs Loopdocs).  But just so you’re aware, dexcom’s servers had an outage which is causing this message. You can delete your dexcom share account from within your CGM section of Loop settings, and that will stop this error from showing in your Loop. Just have your transmitter ID entered and not the share account. 👍

**Comment by ashbyakgm-marie** [comment]
Thank you so much!

Any Ashby
713-503-1180

________________________________

**Comment by marionbarker** [comment]
This issue should be closed.

**Comment by ashbyakgm-marie** [comment]
Yes please close
