### ISSUE TITLE
Please Clarify Open Loop Page

### ISSUE THREAD

**Issue by marionbarker** [LoopKit/loopdocs#484]
See this issue opened by Nuddel69: https://github.com/LoopKit/Loop/issues/1827

This is a loopdocs issue, not a code issue.  Continuing the conversation here.

**Comment by marionbarker** [comment]
Please read the issue posted above for the first few conversational exchanged.

**Comment by marionbarker** [comment]
Open Loop is a time to check your settings before enabling Closed Loop. If you are running high, then your basal rate is probably too low. The first thing to get right is basal. If the suggested correction (using manual bolus) is too small to bring glucose back in line, then it can be a combination of too large a sensitivity number (ISF in mmol/L/U) compounded by too low a basal rate. 

For right now:
 * If glucose is high, hit the manual bolus button in the toolbar to add insulin (Loop will suggest and you can override in the Bolus screen)
 * If glucose is low or dropping, tap on the pump icon and select Manual Temp Basal (default is 0 U/hr for half hour, you can accept, modify or cancel the request in the screen)
 * When preparing for a meal, enter carbs, review bolus suggestion and accept or override it

Then over time, modify settings as needed so that Loop predictions and recommendations are more in line with what actually happens for you. When your settings are pretty good, you can do some fine tuning in closed loop mode. This is very different from using a manual pump, so take some time.

More info:
The developers never intended this feature, that they used while initially testing the system, to be used as a "training" tool. But the fact that it was in LoopDocs meant people began to use it as such. But there were no safeguards - people accidentally enacted insulin delivery when they did not mean to.

The bit about Loop 2.2.x was put in there for Loopers who are using that version and explaining why they need to be careful. 

For a long time, LoopDocs suggested people use that "debug" feature to learn Loop. That suggestion has been removed in preparation for Loop 3.

**Comment by Nuddel69** [comment]
This clarifies the issue and use of open-loop. Thank you!

**Comment by marionbarker** [comment]
Closing this issue.  Open Loop page was updated several time since this issue was opened.
