### ISSUE TITLE
Clarify Nightscout Process in Intro

### ISSUE THREAD

**Issue by pbackstrom** [LoopKit/loopdocs#49]
Sorry, I'm nowhere near being able to fork and use python yet.
Suggested change for 2nd sentence in https://loopkit.github.io/loopdocs/nightscout/overview/
Right now it just says that Nightscout is an app, making it sound like you just get it from the store and you're ready to go:

To set it up, you get an account on a free server and follow instructions to build the application there.  Then you can access it with a web browser or the Nightscout app from the iPhone App Store.  Once set up, the site can be accessed by anyone that you share your unique Nightscout URL with.

**Comment by Kdisimone** [comment]
I think the confusion is around the word "app"...the nightscout code itself is referred to as an "app" within heroku. I will add some clarifying language. Thanks

And...I'll challenge you that you ARE able to fork and follow the directions to set it up. Putting a comment in Github is harder than building the NS app. No python involved. No code experience needed. Just follow the screenshots and you can have it built no problems.

**Comment by pbackstrom** [comment]
Hi Katie, thanks for the response.

I was in fact able to build Nightscout, but not till I understood a bigger picture of what was going on, by asking on Facebook.  The paragraph I submitted was a suggestion for the documentation, a result, not a cause.

My comment about forking and python was about making a proposed change to the documentation myself.  I got scared off by the read me on https://github.com/LoopKit/loopdocs — between the python, pypy (at least I’ve heard of Python) and the various version cautions, I thought my chances weren’t too good at this point.  I wound up submitting a second suggestion on Github as well.

Thanks again,
Paul


On Sep 3, 2019, at 11:35 AM, katie disimone <notifications@github.com<mailto:notifications@github.com>> wrote:


I think the confusion is around the word "app"...the nightscout code itself is referred to as an "app" within heroku. I will add some clarifying language. Thanks

And...I'll challenge you that you ARE able to fork and follow the directions to set it up. Putting a comment in Github is harder than building the NS app. No python involved. No code experience needed. Just follow the screenshots and you can have it built no problems.
