### ISSUE TITLE
Clarify "preferred source" is for MM Only

### ISSUE THREAD

**Issue by pbackstrom** [LoopKit/loopdocs#50]
Two places in the docs say to set your Preferred Source setting in the Loop app to Event History.  A number of us have lost time trying to find it on our Omnipod apps.  If someone would add "(Minimed Only)" in those places to clarify, it would help.
Thanks.
(Maybe one day I'll be able to set up to modify documentation but I'm still too new, just got Nightscout running today after several false starts...)

**Comment by metahgva** [comment]
Hello @pbackstrom, can you link the two places? I can make the change.

**Comment by pbackstrom** [comment]
@metahgva they are

https://loopkit.github.io/loopdocs/troubleshooting/priming/#site-changes
Priming Events and IOB

https://loopkit.github.io/loopdocs/operation/loop-settings/displays/#reservoir-and-event-history
Active Insulin Chart

Thank you.

**Comment by metahgva** [comment]
Should be done, can you review?

**Comment by pbackstrom** [comment]
Both look good, thanks.

**Comment by marionbarker** [comment]
This has been fixed.  The issue should be closed
