### ISSUE TITLE
Can't get code for Test Flight

### ISSUE THREAD

**Issue by latainethomas** [LoopKit/loopdocs#575]
Trying to up load my rebuild and haven't got a code to redeem for Test Flight

**Comment by marionbarker** [comment]
I don’t know what you are asking.

**Comment by marionbarker** [comment]
The first time you send out an app via TestFlight, you have to redeem the code. For updates, it just appears in the TestFlight app on your phone (but you should get 2 emails, one from Apple and one from TestFlight) saying the build is ready. It can take some time (allow an hour) for these to show up.

I have had one instance where the build never was processed by TestFlight. I tried building again the next day and it worked fine. 

* If you have automatic updates enabled on the TestFlight app on your phone, the new version of the app automatically appears on your phone - no action required on your part
* If not, you need to open TestFlight and install the new build.

If this was your question, I'll look into updating the docs to make this more clear.
If not, help me understand what you were asking.

**Comment by latainethomas** [comment]
Looking for code to openTest Flight  for first time my Loop build has been done and ready to test since 1-22-23  Without  a code to redeem I test flight won't open

**Comment by marionbarker** [comment]
You can delete yourself from the Internal Testers group and add yourself back.
I think you can also resend an invitation (but I'm not sure how to trigger that). It might be if you haven't downloaded the app, the resend is an option.

(I deleted and added adam who is a fake person I use for test phones.)
![testflight-resend-invitation](https://user-images.githubusercontent.com/19607791/218808269-d62be16a-68d2-4c86-ae0b-162aca4ac5e0.png)

**Comment by marionbarker** [comment]
@latainethomas Were you able to get your build working with TestFlight?
If yes 
- did my suggestion help? 
- was something else the key to your success?

If no
* do you want additional help?
* feel free to PM me on zulipchat or FB messenger
  * I'm trying to improve the docs but I need to know what does and does not work

**Comment by marionbarker** [comment]
Have not heard any more requests for help so will close this issue.
