### ISSUE TITLE
Create Certificates error despite GH_PAT token "workflow" scope enabled

### ISSUE THREAD

**Issue by jgietl12** [LoopKit/loopdocs#761]
First time building Loop using the browser method. I'm trying to Create Certificates in the LoopWorkspace, but the workflow keeps failing. I followed the steps in Loop Docs (https://loopkit.github.io/loopdocs/gh-actions/gh-errors/#error-missing-repository-access) to ensure my token settings were correct, but I can't seem to get past the error. Please help!

jgietl12

**Comment by marionbarker** [comment]
Try repeating the create certificates. Might be a temporary GitHub glitch.
