### ISSUE TITLE
Directly address mac/xcode-build-to-browser-build use case 

### ISSUE THREAD

**Issue by tabula-raza** [LoopKit/loopdocs#857]
I am a current Loop user who has built Loop on a mac with xcode until now. I want to begin updating/rebuilding using the browser method now. I could not find any language addressing this use case in the Update/Rebuild FAQ page or either of the "Update/Rebuild with" pages (where I expected to find it.) I also ran a search for the string "replace the current app" from the pop-up modal I got in TestFlight (mentioned below) to find any page that addressed that scenario and got no results.

My hunch is that if I get a "You already have this app installed" pop-up modal in TestFlight (which I got before stopping), that's a good sign and indicates I'm building over the existing version of the app on my phone and retaining settings/configuration/device connections? But it would be reassuring to see this (presumably common?) use case addressed head on.

**Comment by marionbarker** [comment]
closed with PR #859
